version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/node"          # Location of package manifests
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "node"
        versions: [">= 17.x"]

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/dotnet"        # Location of package manifests
    schedule:
      interval: "daily"
      time: "13:40"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "mcr.microsoft.com/dotnet/sdk"
        versions: [">= 7.x"]
      - dependency-name: "mcr.microsoft.com/dotnet/aspnet"
        versions: [">= 7.x"]        
