version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "15:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "node"
        versions: [">= 17.x"]
